backend:
  name: git-gateway
  branch: main # Assure-toi que ta branche GitHub s'appelle bien main

media_folder: "images" # Où seront stockées les photos
public_folder: "/images"

collections:
  - name: "projets"
    label: "Mes Projets"
    folder: "projets" # Les données de tes albums seront ici
    extension: "json" # On enregistre en format JSON
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Titre du Projet", name: "title", widget: "string"}
      - {label: "Image à la Une", name: "thumbnail", widget: "image"}
      - {label: "Date du tournage", name: "date", widget: "datetime"}
      - {label: "Description", name: "body", widget: "markdown"}